### ISSUE TITLE
Add Covid and Flu Vaccine Charts

### ISSUE THREAD

**Issue by tclarke104** [QuartzSoftwareLLC/realtime-caserates#2]

**Comment by tclarke104** [comment]
Looks like I don't have write access to create a new branch. Can't make PR. But here are the two files. If you just drag them into the project it will be the changes you need
[changes.zip](https://github.com/user-attachments/files/17500849/changes.zip)

**Comment by tclarke104** [comment]
@jacobaclarke

**Comment by jacobaclarke** [comment]
Looks great
